# Generated by Django 4.2.1 on 2023-06-04 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(max_length=1000)),
                ('EMAIL_HOST_USER', models.CharField(max_length=1000)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=1000)),
                ('EMAIL_PORT', models.CharField(max_length=1000)),
                ('EMAIL_USE_TLS', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
